server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    com.nbclass: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN
#  file: log/zb-shiro.log
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zb-shiro?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 7000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.nbclass.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.nbclass.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql