
spring:
  thymeleaf:
    cache: false
    #非严格模式的HTML语法检查
    mode: LEGACYHTML5
  datasource:
    druid:
#      db-type: h2
#      driver-class-name: org.h2.Driver
#      url: jdbc:mysql://127.0.0.1:3306/noteblogv3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: noteblog
      password: v4
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    multipart:
      max-file-size: 10MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      force-request: true
  resources:
    static-locations: file:f://upload/
  mvc:
    favicon:
      enabled: false
  application:
    name: noteblogv3
  h2:
    console:
      enabled: true
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 2000
    max-threads:  2000
