xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7070/xxl-job-admin
    executor:
      appname: wk-job
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:
spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    database: 12
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/wk_crm_single?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password}

